version: '3.8'
services:
  db:
    image: your-dockerhub-username/database:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    image: your-dockerhub-username/backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: your-dockerhub-username/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
